CREATE TABLE TYPE
(
    ID  INTEGER AUTO_INCREMENT,
    NOM VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE ESPECE
(
    ID                 INTEGER AUTO_INCREMENT,
    NOM                VARCHAR(255),
    POKEDEX            INTEGER,
    ID_TYPE_PRINCIPAL  INTEGER,
    ID_TYPE_SECONDAIRE INTEGER,
    ID_EVOLUTION_DE     INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_TYPE_PRINCIPAL) REFERENCES TYPE (ID),
    FOREIGN KEY (ID_TYPE_SECONDAIRE) REFERENCES TYPE (ID),
    FOREIGN KEY (ID_EVOLUTION_DE) REFERENCES ESPECE (ID)
);



