INSERT INTO TYPE(NOM) VALUES ('NORMAL');
INSERT INTO TYPE(NOM) VALUES ('VOL');
INSERT INTO TYPE(NOM) VALUES ('EAU');

INSERT INTO ESPECE( NOM, POKEDEX, ID_TYPE_PRINCIPAL, ID_TYPE_SECONDAIRE, ID_EVOLUTION_DE)
VALUES ('ROUCOUL', 16, 1, 2, null);
INSERT INTO ESPECE( NOM, POKEDEX, ID_TYPE_PRINCIPAL, ID_TYPE_SECONDAIRE, ID_EVOLUTION_DE)
VALUES ('ROUCOUPS', 17, 1, 2, 1);
INSERT INTO ESPECE( NOM, POKEDEX, ID_TYPE_PRINCIPAL, ID_TYPE_SECONDAIRE, ID_EVOLUTION_DE)
VALUES ('CARAPUCE', 7, 3, null, null);

INSERT INTO DRESSEUR(NOM) VALUES ('Sasha');

INSERT INTO POKEMON(SURNOM, NIVEAU, ID_DRESSEUR, ID_ESPECE) VALUES('ROUCOOOOOL', 1, 1, 1);
INSERT INTO POKEMON(SURNOM, NIVEAU, ID_DRESSEUR, ID_ESPECE) VALUES(null, 18, 1, 2);


INSERT INTO ATTAQUE(NOM, PUISSANCE, ID_TYPE) VALUES ('CHARGE',30,1);
INSERT INTO ATTAQUE(NOM, PUISSANCE, ID_TYPE) VALUES ('PICIC',35,2);

INSERT INTO PEUT_LANCER(ID_ATTAQUE, ID_POKEMON) VALUES(1,1);
INSERT INTO PEUT_LANCER(ID_ATTAQUE, ID_POKEMON) VALUES(1,2);
INSERT INTO PEUT_LANCER(ID_ATTAQUE, ID_POKEMON) VALUES(2,2);


INSERT INTO UTILISATEUR (LOGIN,MDP,ROLE) VALUES ('TOTO', 'TATA', 'USER');
