
INSERT INTO TYPE(NOM) VALUES ('NORMAL');
INSERT INTO TYPE(NOM) VALUES ('VOL');
INSERT INTO TYPE(NOM) VALUES ('EAU');

INSERT INTO ESPECE( NOM, POKEDEX, ID_TYPE_PRINCIPAL, ID_TYPE_SECONDAIRE, ID_EVOLUTION_DE)
VALUES ('ROUCOUL', 16, 1, 2, null);
INSERT INTO ESPECE( NOM, POKEDEX, ID_TYPE_PRINCIPAL, ID_TYPE_SECONDAIRE, ID_EVOLUTION_DE)
VALUES ('ROUCOUPS', 17, 1, 2, 1);
INSERT INTO ESPECE( NOM, POKEDEX, ID_TYPE_PRINCIPAL, ID_TYPE_SECONDAIRE, ID_EVOLUTION_DE)
VALUES ('CARAPUCE', 7, 3, null, null);
